### PR TITLE
Support Caddy v2.5.2 release

### PR DESCRIPTION
**Pull request by justusbunsi**
With Caddy release v2.5.2, this plugin does not build anymore when using `xcaddy build --with github.com/Baldinof/caddy-supervisor`. Looks like https://github.com/caddyserver/caddy/commit/10f85558ead15e119f8e9abd81c8ad55eb865f8b causes it due to the change of package `github.com/antlr/antlr4`.

Its a breaking change as it requires Caddy version v2.5.2 and higher.

### CODE REVIEW

**Comment by francislavoie** [comment]
I don't think that's true, actually.

Upgrade your version of xcaddy to v0.3.0 and it should be fine.

**Comment by justusbunsi** [comment]
Hi. That's odd. I've used following Dockerfile spec that reproduces the issue:

```Dockerfile
FROM golang:1.17.2-bullseye
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@v0.3.0
RUN xcaddy build --with github.com/baldinof/caddy-supervisor@latest
```

I also tried with `github.com/caddyserver/xcaddy/cmd/xcaddy@latest` just to be sure it doesn't work.

Both attempts result in following error

```text
#0 35.47 caddy imports
#0 35.47        github.com/baldinof/caddy-supervisor imports
#0 35.47        github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile imports
#0 35.47        github.com/caddyserver/caddy/v2/modules/caddyhttp imports
#0 35.47        github.com/google/cel-go/parser imports
#0 35.47        github.com/antlr/antlr4/runtime/Go/antlr loaded from github.com/antlr/antlr4/runtime/Go/antlr@v0.0.0-20220626175859-9abda183db8e,
#0 35.47        but go 1.16 would fail to locate it:
#0 35.47        ambiguous import: found package github.com/antlr/antlr4/runtime/Go/antlr in multiple modules:
#0 35.47        github.com/antlr/antlr4 v0.0.0-20200503195918-621b933c7a7f (/go/pkg/mod/github.com/antlr/antlr4@v0.0.0-20200503195918-621b933c7a7f/runtime/Go/antlr)
#0 35.47        github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220626175859-9abda183db8e (/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20220626175859-9abda183db8e)      
#0 35.47
#0 35.47 To proceed despite packages unresolved in go 1.16:
#0 35.47        go mod tidy -e
#0 35.47 If reproducibility with go 1.16 is not needed:
#0 35.47        go mod tidy -compat=1.17
#0 35.47 For other options, see:
#0 35.47        https://golang.org/doc/modules/pruning
```

**Comment by justusbunsi** [comment]
So many ways to have a successful Caddy build. 😃 Thanks for your fast response. I can confirm that using Go 1.18 works. I didn't knew there is a `caddy:builder` image tag. I'm switching to that image.

**Comment by justusbunsi** [comment]
Closing the PR as it's not necessary. Thanks again.

**Comment by Baldinof** [comment]
Thank you @francislavoie I would not have been as efficient :D 

And thanks @justusbunsi for the report / fix attempt :)

**Pull request closed without merging**
